### PR TITLE
Changes in PRM/Astar files.

### PR DESCRIPTION
**Pull request by Srujan-D**
1) The PRM, PRM-star and A-star files have been updated to integrate the new Graph class in utils.graph.
2) Hash and Eq methods have been added to RobotState (utils.RobotState).
3) Velocity attribute added to RobotState (utils.RobotState)
4) Minor changes in incorrect doc-strings in Velocity and RobotState classes (utils).

### CODE REVIEW

**Comment by threewisemonkeys-as** [comment]
Good work!

**Comment by threewisemonkeys-as** [comment]
Are all the doc files generated?

**Comment by Srujan-D** [comment]
> Are all the doc files generated?

I'm not sure if _all_ are generated. I can see some at the top of "files changed" option. How do I ensure if all are generated properly? I thought that happens automatically when i create a PR.

**Comment by threewisemonkeys-as** [comment]
Yeah, i need to add that actually

**Comment by threewisemonkeys-as** [comment]
Running `tox -e docs` should do it

**Comment by threewisemonkeys-as** [comment]
Lmk if any file are changed. If not, Ill merge this

**Comment by Srujan-D** [comment]
> Lmk if any file are changed. If not, Ill merge this

I'm getting confused with the doc files. Can you please check your Slack?

**Pull request merged**
